### ISSUE TITLE
Implement Level Map + Collectables and have progress saved after Quitting

### ISSUE THREAD

**Issue by EthanDonley** [EthanDonley/55project-reduxed#4]
I saw someone create a menu map for one of their platformers for comp 55 and have a collectable system that can be saved after completing levels. Being able to swap between levels is easy to implement as it is affected by the panes put in place by the starter code and we have a built in level id. I want to also tryout the mechanic that the other platforming team in my class did where even after quitting the program it saves your progress on which levels you unlocked and how many collectables you got for each level. Obviously WAY more levels will be created for the platformer so being able to traverse through a lot of levels and maintain progress after quitting would be incredibly helpful and make it feel like you are progressing.

**Comment by onzfonz** [comment]
Yeah keeping the progress here sounds good.
You should do this one
